version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatbot-test-vectorstore
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data